### ISSUE TITLE
Degrees in gradients ?

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#814]
I was trying to do a directional gradient but Compass keeps throwing the same error no matter what angle I type in. Here is my code :

```
@mixin gradient-directional($start, $end, $angle: 45deg)
{
    background-color: $end
    @include background-image(linear-gradient($angle, $start, $end));
}
```

Am I doing something wrong or ?

**Comment by chriseppstein** [comment]
What error are you getting?

**Comment by Anahkiasen** [comment]
"Cannot determine the opposite direction of 45deg"

**Comment by chriseppstein** [comment]
It works for me on compass 0.12. Are you on 0.11 still?

**Comment by Anahkiasen** [comment]
No I'm up to date on the latest commits of compass. Even if I simplify the code, no mixin or nothing and just do this :

```
body
    +background-image(linear-gradient(45deg, black, white))
```

I get the error. Pretty weird. I'm in a normal environnement, no plugin, basic sass stylesheet.

**Comment by chriseppstein** [comment]
Actually, I do see the warning. but the output still works.

I need to iterate on this anyway. The official syntax has changed.

**Comment by scottdavis** [comment]
also that warning is a child of that PR a month or so ago that "fixed" trig functions you may need to revisit it

**Comment by bleadof** [comment]
I get a similar error.

``` scss
$center_background_color: #f2f2f2;
$center_content_gradient_color: #bebebe;
$center_content_gradient_color2: #dedede;
$center_content_gradient_height: 14px;
$center_content_gradient_2_color_change: 5px;

.centerContent {
    @include background-image(linear-gradient($center_content_gradient_color,
                                              $center_content_gradient_color2 $center_content_gradient_2_color_change,
                                              $center_background_color $center_content_gradient_height),
                              linear-gradient(180deg, 
                                              $center_content_gradient_color,
                                              $center_content_gradient_color2 $center_content_gradient_2_color_change,
                                              $center_background_color $center_content_gradient_height));
}
```

Cannot determine the opposite position of: 180deg
Cannot determine the opposite position of: 180deg
[NoMethodError on line 333 of /Library/Ruby/Gems/1.8/gems/compass-0.12.1/lib/compass/sass_extensions/functions/gradient_support.rb](https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/gradient_support.rb#L333): undefined method `first' for 180:Fixnum

```
alumiini:compass tarmo$ compass --version
Compass 0.12.1 (Alnilam)
```

**Comment by MattyBalaam** [comment]
I'm using compass-0.13.alpha.0 but I'm getting this error, should this version work too?

**Comment by mirisuzanne** [comment]
No. 0.13.alpha.0 was pushed before this fix. It is fixed on the master branch, and will work in the next 0.13 pre-release. In the meantime you can set `$support-for-original-webkit-gradients  : false;` - which I recommend in any case.
