### ISSUE TITLE
Compass does not work with Rails 3.1 and the asset pipeline disabled

### ISSUE THREAD

**Issue by lloydk** [Compass/compass#522]
```
=> Booting WEBrick
=> Rails 3.1.0 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/railtie/configuration.rb:78:in `method_missing': undefined method `sass' for #<Rails::Application::Configuration:0x8f59f58> (NoMethodError)
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.alpha.0/lib/compass/configuration/helpers.rb:82:in `block in configure_rails!'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.alpha.0/lib/compass/configuration/helpers.rb:81:in `each'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.alpha.0/lib/compass/configuration/helpers.rb:81:in `configure_rails!'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/compass-0.12.alpha.0/lib/compass/app_integration/rails/actionpack31/railtie.rb:86:in `block in <class:Railtie>'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `instance_exec'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `run'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `each'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `run_initializers'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/application.rb:92:in `initialize!'
    from /home/lloydk/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/lloydk/work/test31/config/environment.rb:5:in `<top (required)>'
```

I generated a new Rails 3.1 (release) application. Then added compass 0.12.alpha.0 to my Gemfile and commented out the gems in the asset group (because sass-rails requires the asset pipeline to be enabled).

```
source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'therubyracer'
gem 'compass', '0.12.alpha.0'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
#  gem 'sass-rails', "  ~> 3.1.0"
#  gem 'coffee-rails', "~> 3.1.0"
#  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
```

Edited config/application.rb to disable the asset pipeline:

```
    # Enable the asset pipeline
    config.assets.enabled = false
```

It looks like the code that is in the [configure_rails!](https://github.com/chriseppstein/compass/blob/master/lib/compass/configuration/helpers.rb#L80) method should only be executed if sass-rails is installed.

**Comment by scottdavis** [comment]
merged already closing

**Comment by lloydk** [comment]
This issue should be kept open until compass actually works with the asset pipeline disabled. Additional changes are necessary to get things working.

**Comment by scottdavis** [comment]
oh i saw chris merged in your change i figured it was finished he didn't comment

**Comment by colszowka** [comment]
Since I am using precompiled assets via s3/cloudfront, I managed to work around this by moving the compass gem to the assets group, which is not used in production since `config/application.rb` states this: `Bundler.require *Rails.groups(:assets => %w(development test))`.
