### ISSUE TITLE
radial-gradient mixin breaks when passed css syntax

### ISSUE THREAD

**Issue by slackersoft** [Compass/compass#1776]
We have compass installed for our use, but when we pull in another dependency that doesn't expect to have compass, but uses scss and radial-gradient, compass breaks their call to radial-gradient. We were able to reproduce this by just copying one of the examples on how to use radial-gradient from [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient). We only started seeing this when upgrading to 1.0.0.rc.0 from 1.0.0.alpha.20.

``` css
body {
  background: radial-gradient(ellipse farthest-corner at 45px 45px , #00FFFF 0%, rgba(0, 0, 255, 0) 50%, #0000FF 95%);
}
```

The error that we get is:

```
undefined method `empty?' for #<Sass::Script::Value::String:0x007fd8fb1d8838>
```

**Comment by chriseppstein** [comment]
Duplicate of #1766

**Comment by chriseppstein** [comment]
Just released 1.0.1 with this fix.

**Comment by slackersoft** [comment]
Awesome, thanks!
